### ISSUE TITLE
IProgress

### ISSUE THREAD

**Issue by MaximGoncharukSW** [kirmir/WpfAsyncPack#1]
Could you please implement supporting of IProgress interface? It would be useful to track progress of executed command.

**Comment by kyrylomyr** [comment]
I've implemented the `ProgressiveAsyncCommand` in the new version **1.4.0**. It is derived from the `AsyncCommand` (thus, contains the same functionality), but also supports `IProgress<T>`. How to use it can be seen in the sample project **WeatherApp** in the repository. Basically, it looks like this:

``` csharp
MyCommand = new ProgressiveAsyncCommand<int>(
    async progress =>
    {
        // Pass progress parameter to the service that reports progress.
        var weather = await _service.GetWeatherAsync(progress);
        // ...
    },
    progressValue =>
    {
        // Update property bound to the ProgressBar.
        UpdateWeatherProgress = progressValue;
    },
    x => InitCommand.Task.IsNotRunning);
```
